services:
      admin.services:
          class: AppBundle\Admin\ServicesAdmin
          arguments: [~, AppBundle\Entity\Services, ~]
          tags:
              - {
                  name: sonata.admin,
                  manager_type: orm,
                  label: Services,
                  group: "Services",
                  icon: '<i class="fa fa-users"></i>'
                 }
          public: true
      admin.items:
          class: AppBundle\Admin\ItemsAdmin
          arguments: [~, AppBundle\Entity\Items, ~]
          tags:
              - {
                  name: sonata.admin,
                  manager_type: orm,
                  label: Items,
                  group: "Items",
                  icon: '<i class="fa fa-users"></i>'
                 }
          public: true
      admin.about:
          class: AppBundle\Admin\AboutAdmin
          arguments: [~, AppBundle\Entity\About, ~]
          tags:
              - {
                  name: sonata.admin,
                  manager_type: orm,
                  label: About,
                  group: "About",
                  icon: '<i class="fa fa-users"></i>'
                 }
          public: true
      admin.contact:
          class: AppBundle\Admin\ContactAdmin
          arguments: [~, AppBundle\Entity\Contact, ~]
          tags:
              - {
                  name: sonata.admin,
                  manager_type: orm,
                  label: Contact,
                  group: "Contact",
                  icon: '<i class="fa fa-users"></i>'
                 }
          public: true
      admin.siteInfo:
          class: AppBundle\Admin\SiteInfoAdmin
          arguments: [~, AppBundle\Entity\SiteInfo, ~]
          tags:
              - {
                  name: sonata.admin,
                  manager_type: orm,
                  label: Site Info,
                  group: "Site Info",
                  icon: '<i class="fa fa-users"></i>'
                 }
          public: true



